# Databricks notebook source
# MAGIC %md
# MAGIC 
# MAGIC #Overview 
# MAGIC This notebook calls the registered XGBoost that was generated as a part of the `STATUS_turbines_gold-2021_12_13-13_31` AutoML experiment. Registered model details can be found [here](https://e2-demo-field-eng.cloud.databricks.com/?o=1444828305810485#mlflow/models/doan_ml_flow_example/versions/1), and we test the pandas and spark prediction code generated [here](https://e2-demo-field-eng.cloud.databricks.com/?o=1444828305810485#mlflow/experiments/2492745853146109/runs/6dfa5d5baf334e89a79129dcc6386a4a).
# MAGIC 
# MAGIC Currently, the model prediction calls work on Pandas dataframes, but not on Spark dataframes, as shown below

# COMMAND ----------

#generate a dataset for testing by sampling the training set
sample_df = spark.read.table("dec21_flightschool_team2.turbines_silver").sample(0.0001)

# COMMAND ----------

sample_df.count()

# COMMAND ----------

# DBTITLE 1,Predict using Pandas (works)
#convert to pandas dataframe and call logged model for predictions 
data = sample_df.toPandas()

#uses code snippet provided under MlFlow -> Make Predictions -> Pandas Dataframe at https://e2-demo-field-eng.cloud.databricks.com/?o=1444828305810485#mlflow/experiments/2492745853146109/runs/6dfa5d5baf334e89a79129dcc6386a4a
import mlflow
logged_model = 'runs:/6dfa5d5baf334e89a79129dcc6386a4a/model'

# Load model as a PyFuncModel.
loaded_model = mlflow.pyfunc.load_model(logged_model)

# Predict on a Pandas DataFrame.|
import pandas as pd
predictions = loaded_model.predict(pd.DataFrame(data))
predictions_dataframe = pd.DataFrame(predictions, columns=['predictions'])
predictions_dataframe.head()

# COMMAND ----------

# DBTITLE 1,Predict using Spark DataFrame (does not work)
#uses code snippet provided under MlFlow -> Make Predictions -> Spark Dataframe at https://e2-demo-field-eng.cloud.databricks.com/?o=1444828305810485#mlflow/experiments/2492745853146109/runs/6dfa5d5baf334e89a79129dcc6386a4a
import mlflow
logged_model = 'runs:/6dfa5d5baf334e89a79129dcc6386a4a/model'

# Load model as a Spark UDF.
loaded_model = mlflow.pyfunc.spark_udf(spark, model_uri=logged_model)

# Predict on a Spark DataFrame.
columns = list(sample_df.columns)
sample_df.withColumn('predictions', loaded_model(*columns)).collect()

# COMMAND ----------

# MAGIC %md
# MAGIC # Other Notes
# MAGIC 
# MAGIC I was also able to recreate the error using the `Use model for inference` option for the registered model. See the [Inference-Autogenerated](https://e2-demo-field-eng.cloud.databricks.com/?o=1444828305810485#notebook/2492745853152076/command/2492745853152089) notebook in this repo for additional details

# COMMAND ----------


